/**************************************************************
 ********          THIS IS A GENERATED FILE         ***********
 **************************************************************/

package org.qeo.system;

/**
 * this is the device ID generated by Qeo.
 */
public class DeviceId
{
    /**
     * Upper 64-bit of identifier.
     */
    public long upper;

    /**
     * Lower 64-bit of identifier.
     */
    public long lower;

    public DeviceId()
    {
    }

    @Override
    public boolean equals(Object obj)
    {
        if (obj == this) {
            return true;
        }
        if ((obj == null) || (obj.getClass() != this.getClass())) {
            return false;
        }
        final DeviceId myObj = (DeviceId)obj;
        if (upper != myObj.upper) {
            return false;
        }
        if (lower != myObj.lower) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (upper ^ (upper >>> 32));
        result = prime * result + (int) (lower ^ (lower >>> 32));
        return result;
    }
}
